import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { inflateSync } from "node:zlib";
import { PDFDocument, PDFName, PDFRawStream } from "pdf-lib";
import { parseInstructions } from "../src/csv";
import { DIST_MACHINE, loadMachine } from "../src/machine";
import { cardGroups } from "../src/mixing";

// The committed dummy chart, not `data/washing-instructions.csv` — that one is
// gitignored, so on a fresh clone and in CI it is not there to read.
const CSV = "data/washing-instructions.csv.dist";

/** The six the README links, regenerated by `bun run examples`. */
const EXAMPLES = [
  "washing-instructions-phone.pdf",
  "washing-instructions-phone-washing.pdf",
  "washing-instructions-phone-ironing.pdf",
  "washing-instructions-print.pdf",
  "washing-instructions-print-washing.pdf",
  "washing-instructions-print-ironing.pdf",
];

/**
 * Every word a PDF actually draws.
 *
 * @react-pdf writes its text as hex-encoded `TJ` runs inside a Flate-compressed
 * content stream, so this inflates each page and pulls the strings back out.
 * Crude — it knows nothing about position, so a two-column row reads as one
 * line — but a sheet that has stopped drawing the iron is a sheet with no iron
 * words in it, and nothing softer than reading the ink proves that.
 */
async function words(pdf: Uint8Array): Promise<string> {
  const doc = await PDFDocument.load(pdf);
  return doc
    .getPages()
    .map((page) => {
      const stream = doc.context.lookup(page.node.get(PDFName.of("Contents")));
      if (!(stream instanceof PDFRawStream)) return "";
      const raw = Buffer.from(inflateSync(stream.contents)).toString("latin1");
      return [...raw.matchAll(/\[((?:\s*<[0-9a-fA-F]*>\s*-?[\d.]*)+)\]\s*TJ/g)]
        .map((run) =>
          [...(run[1] as string).matchAll(/<([0-9a-fA-F]*)>/g)]
            .map((chunk) => Buffer.from(chunk[1] as string, "hex").toString("latin1"))
            .join(""),
        )
        .join(" ");
    })
    .join(" ");
}

/**
 * What a document actually draws, page by page: its size and a hash of its
 * content stream.
 *
 * Not the file's bytes. Two runs over the same input write the same streams
 * but number them differently — @react-pdf writes them as they resolve — and
 * each run stamps its own creation date and file ID, so a byte comparison
 * fails on everything except what it was meant to catch. The page tree is
 * stable, and every stream hanging off it is identical.
 */
async function drawing(pdf: Buffer): Promise<string[]> {
  const doc = await PDFDocument.load(pdf);
  return doc.getPages().map((page) => {
    const contents = page.node.get(PDFName.of("Contents"));
    const stream = contents ? doc.context.lookup(contents) : undefined;
    const ink = stream instanceof PDFRawStream ? Bun.hash(stream.contents).toString(16) : "blank";
    return `${Math.round(page.getWidth())}x${Math.round(page.getHeight())} ${ink}`;
  });
}

/**
 * The outer test: run the tool exactly as a person would and check the two
 * PDFs that come out. Anything below this — parsing, mixing rules, layout —
 * only exists to make this pass.
 */
describe("bun run generate", () => {
  let out: string;
  let exitCode: number;
  let stdout: string;

  beforeAll(async () => {
    out = await mkdtemp(join(tmpdir(), "washing-"));
    const result = Bun.spawnSync({
      // Both files named explicitly. The defaults prefer your own chart and
      // your own machine, which is right for a person at a terminal and wrong
      // for a test that has to mean the same thing on every clone.
      cmd: ["bun", "run", "src/cli.ts", CSV, "--out", out, "--machine", DIST_MACHINE],
      stdout: "pipe",
      stderr: "pipe",
    });
    exitCode = result.exitCode;
    stdout = result.stdout.toString() + result.stderr.toString();
  }, 120_000);

  afterAll(async () => {
    await rm(out, { recursive: true, force: true });
  });

  test("exits cleanly", () => {
    expect(stdout).not.toContain("error");
    expect(exitCode).toBe(0);
  });

  test("writes a phone PDF that is one continuous page", async () => {
    const pdf = await PDFDocument.load(await readFile(join(out, "washing-instructions-phone.pdf")));
    expect(pdf.getPageCount()).toBe(1);

    const page = pdf.getPage(0);
    expect(page.getWidth()).toBeCloseTo(244, 0);
    // Tall enough to be a scroll sheet, but bisected down rather than padded.
    expect(page.getHeight()).toBeGreaterThan(page.getWidth() * 8);
  });

  test("writes a printable PDF, every page A4", async () => {
    const pdf = await PDFDocument.load(await readFile(join(out, "washing-instructions-print.pdf")));
    const cards = cardGroups(
      parseInstructions(await readFile(CSV, "utf8"), await loadMachine(DIST_MACHINE)),
    ).length;

    // The reference sheet, then the cards flowing over as many sheets as they
    // need. Two fit comfortably today, but a wordy row can push that to one.
    expect(pdf.getPageCount()).toBeGreaterThanOrEqual(1 + Math.ceil(cards / 2));
    expect(pdf.getPageCount()).toBeLessThanOrEqual(1 + cards);

    for (const page of pdf.getPages()) {
      expect(page.getWidth()).toBeCloseTo(595.28, 0);
      expect(page.getHeight()).toBeCloseTo(841.89, 0);
    }
  });

  /**
   * The split sheets. One run writes six files: the whole chart, the wash half
   * and the iron half, in each of the two shapes. The halves exist because the
   * two jobs happen in different rooms hours apart, and carrying the drying
   * advice to the ironing board is what makes a card too long to read.
   */
  describe("the washing-only and ironing-only sheets", () => {
    test("writes all six PDFs", async () => {
      for (const name of EXAMPLES) {
        expect(await Bun.file(join(out, name)).exists()).toBe(true);
      }
    });

    test("keeps the phone halves to one page of the same width", async () => {
      for (const name of ["-phone-washing.pdf", "-phone-ironing.pdf"]) {
        const pdf = await PDFDocument.load(
          await readFile(join(out, `washing-instructions${name}`)),
        );
        expect(pdf.getPageCount()).toBe(1);
        expect(pdf.getPage(0).getWidth()).toBeCloseTo(244, 0);
      }
    });

    test("keeps the print halves on A4 with nothing blank", async () => {
      for (const name of ["-print-washing.pdf", "-print-ironing.pdf"]) {
        const pdf = await PDFDocument.load(
          await readFile(join(out, `washing-instructions${name}`)),
        );
        for (const page of pdf.getPages()) {
          expect(page.getWidth()).toBeCloseTo(595.28, 0);
          expect(page.getHeight()).toBeCloseTo(841.89, 0);
          const stream = pdf.context.lookup(page.node.get(PDFName.of("Contents")));
          expect(stream instanceof PDFRawStream ? stream.contents.length : 0).toBeGreaterThan(1000);
        }
      }
    });

    test("the washing sheets say nothing about the iron", async () => {
      for (const name of ["-phone-washing.pdf", "-print-washing.pdf"]) {
        const text = await words(await readFile(join(out, `washing-instructions${name}`)));
        expect(text).toContain("White Towels");
        expect(text).toContain("DETERGENT");
        expect(text).not.toContain("steam zone");
        expect(text).not.toContain("Do not iron");
      }
    });

    test("the ironing sheets say nothing about the machine", async () => {
      for (const name of ["-phone-ironing.pdf", "-print-ironing.pdf"]) {
        const text = await words(await readFile(join(out, `washing-instructions${name}`)));
        expect(text).toContain("White Towels");
        expect(text).toContain("Do not iron");
        expect(text).not.toContain("clockwise from");
        expect(text).not.toContain("SOFTENER");
        expect(text).not.toContain("DRYING");
      }
    });

    /** One card per thermostat position, not one per pile. */
    test("gathers the ironing sheet by where the thermostat points", async () => {
      const text = await words(await readFile(join(out, "washing-instructions-print-ironing.pdf")));
      // Six piles are never ironed. They share the card rather than getting six.
      expect(text).toContain("cotton, linen");
      expect(text.match(/Do not iron/g)?.length).toBeLessThan(3);
    });

    /**
     * The card heading already says do not iron, so a pile whose whole ironing
     * line is "Don't." earns a blank rather than a row that repeats it. A pile
     * that says why keeps the why.
     */
    test("leaves the no-iron rows blank unless they add something", async () => {
      for (const name of ["-phone-ironing.pdf", "-print-ironing.pdf"]) {
        const text = await words(await readFile(join(out, `washing-instructions${name}`)));
        // The piles are still listed — it is the empty second column that changed.
        expect(text).toContain("White Socks");
        expect(text).toContain("Gym Socks");
        // Nothing on the sheet just refuses any more. Capitalised, because
        // "don't press hard" mid-sentence is advice and stays.
        expect(text).not.toContain("Don't");
        // The ones carrying a reason keep it, minus the refusal that led it.
        expect(text).toContain("Ironing crushes the pile flat");
        expect(text).toContain("Elastane starts degrading");
      }
    });

    test("names all six in what it reports", () => {
      for (const name of EXAMPLES) expect(stdout).toContain(name);
    });
  });

  /**
   * The chart has always carried how long each programme runs. It used to
   * appear only in the corner of a card, which is no use when the question is
   * "have I got time before dinner" and you are looking at the pinned sheet.
   */
  test("puts the wash duration on the reference sheet and in the loads", async () => {
    const print = await words(await readFile(join(out, "washing-instructions-print.pdf")));
    expect(print).toContain("Time");
    expect(print).toContain("~2:30");

    const phone = await words(await readFile(join(out, "washing-instructions-phone.pdf")));
    expect(phone).toContain("~0:40");
  });

  test("reports how long each load takes", () => {
    expect(stdout).toMatch(/White \+ White Socks\s+~2:30/);
  });

  /**
   * The README links the PDFs under docs/ rather than describing them, so
   * a reader who opens one is reading the current chart or a lie. This run
   * used the chart and the appliances they were drawn from, so it has to draw
   * what they draw. `bun run examples` is the fix when it does not.
   */
  test("draws the examples committed under docs/", async () => {
    const stale: string[] = [];
    for (const name of EXAMPLES) {
      const fresh = await drawing(await readFile(join(out, name)));
      const committed = await drawing(await readFile(join("docs", name)));
      if (JSON.stringify(fresh) !== JSON.stringify(committed)) stale.push(`docs/${name}`);
    }

    expect(stale).toEqual([]);
  });

  test("reports which piles can share a drum", () => {
    expect(stdout).toContain("Piles that can share a drum");
    expect(stdout).toContain("Dark + Black Socks + Denim");
    expect(stdout).toContain("White + White Socks");
  });

  test("reports the piles that collapsed onto one card", () => {
    expect(stdout).toContain("sharing one card");
    expect(stdout).toContain("Merino Wool + Cashmere Blend");
  });

  test("says which appliances it drew for", () => {
    expect(stdout).toContain("Generic front loader");
  });

  /**
   * A machine with longer programme names once widened the summary table by
   * enough to push the reference sheet a point past A4, and @react-pdf answers
   * a page it cannot fit with an empty sheet rather than an error. Nothing
   * failed: the page count stayed inside its allowed range and the blank sheet
   * only turned up when someone printed it.
   */
  test("prints no blank pages", async () => {
    const pdf = await PDFDocument.load(await readFile(join(out, "washing-instructions-print.pdf")));

    const ink = pdf.getPages().map((page) => {
      const contents = page.node.get(PDFName.of("Contents"));
      const stream = contents ? pdf.context.lookup(contents) : undefined;
      return stream instanceof PDFRawStream ? stream.contents.length : 0;
    });

    expect(ink.filter((bytes) => bytes < 1000)).toEqual([]);
  });
});

/**
 * The whole point of the machine file: the same chart, a different fascia.
 * Nothing in the code knows what a programme is called.
 */
describe("bun run generate --machine", () => {
  test("draws whatever machine it is given", async () => {
    const dir = await mkdtemp(join(tmpdir(), "machine-"));
    const machine = join(dir, "machine.json");
    const chart = join(dir, "chart.csv");

    await writeFile(
      machine,
      JSON.stringify({
        washer: {
          name: "Zanussi ZWF",
          capacity: "7 kg",
          programs: ["Arrêt", "Coton", "Synthétiques", "Laine"],
          temperatures: ["froid", "30", "40"],
          spins: ["0", "1000"],
          options: ["Prélavage"],
        },
        iron: {
          name: "Calor Pro",
          settings: [
            { key: "1", dots: "•", label: "•", detail: "synthétiques", steam: false },
            { key: "2", dots: "••", label: "••", detail: "laine", steam: true },
          ],
        },
      }),
    );
    await writeFile(
      chart,
      "clothing_type,detergent,fabric_softener,temperature,spin,duration,program,options," +
        "ironing,iron_setting,drying,colour_group,mix_tags,notes\n" +
        "Linge blanc,Lessive,no,40,1000,~2:00,Coton,Prélavage,Fer chaud,2,Étendre,white,,\n" +
        "Pulls,Lessive laine,no,30,0,~0:40,Laine,,Ne pas repasser,1,À plat,any,,\n",
    );

    const result = Bun.spawnSync({
      cmd: ["bun", "run", "src/cli.ts", chart, "--out", dir, "--machine", machine],
      stdout: "pipe",
      stderr: "pipe",
    });
    const output = result.stdout.toString() + result.stderr.toString();

    expect(output).toContain("Zanussi ZWF");
    expect(result.exitCode).toBe(0);
    expect(await Bun.file(join(dir, "chart-print.pdf")).exists()).toBe(true);

    await rm(dir, { recursive: true, force: true });
  }, 120_000);

  test("refuses a chart written for a different machine, and says which value", async () => {
    // A fixture rather than data/machine.json: that one is gitignored, so on a
    // fresh clone loadMachine would fall back to the .dist and this would pass
    // by agreeing with itself.
    const dir = await mkdtemp(join(tmpdir(), "other-"));
    const machine = join(dir, "machine.json");
    await writeFile(
      machine,
      JSON.stringify({
        washer: {
          name: "Some Other Washer",
          capacity: "8 kg",
          programs: ["Uit", "Katoen", "Wol"],
          temperatures: ["koud", "30", "60"],
          spins: ["0", "1200"],
          options: ["Extra spoelen"],
        },
        iron: {
          name: "Some Other Iron",
          settings: [
            { key: "1", dots: "•", label: "•", detail: "", steam: false },
            { key: "2", dots: "••", label: "••", detail: "", steam: true },
          ],
        },
      }),
    );

    const result = Bun.spawnSync({
      cmd: ["bun", "run", "src/cli.ts", CSV, "--out", dir, "--machine", machine],
      stdout: "pipe",
      stderr: "pipe",
    });

    expect(result.exitCode).toBe(1);
    expect(result.stderr.toString()).toMatch(/row 2, column "(program|options)"/);

    await rm(dir, { recursive: true, force: true });
  }, 60_000);
});
