import { describe, expect, test } from "bun:test";
import { generateNotes } from "@semantic-release/release-notes-generator";
import releaserc from "../.releaserc.json";

// The release notes are generated by a plugin whose preset arrives as a
// separate pinned package, and the two agree about the shape of a config
// object rather than about a version range. When they stop agreeing the
// generator does not fail: it falls back to no template and writes a heading
// with nothing under it, which is what shipped in v1.0.0 and v1.1.0. So the
// check is on the output, run against the real .releaserc.json rather than a
// copy of it.

function pluginOptions(name: string): Record<string, unknown> {
  for (const plugin of releaserc.plugins) {
    if (Array.isArray(plugin) && plugin[0] === name) return plugin[1] as Record<string, unknown>;
    if (plugin === name) return {};
  }
  throw new Error(`.releaserc.json does not configure ${name}`);
}

const REPO = "https://github.com/alrayyes/washing-instructions";

const notes = await generateNotes(pluginOptions("@semantic-release/release-notes-generator"), {
  commits: [
    { hash: "a".repeat(40), message: "feat(ci): publish the container image\n" },
    { hash: "b".repeat(40), message: "fix(ci): run the image as the mount owner\n" },
    { hash: "c".repeat(40), message: "chore: bump a linter\n" },
  ],
  lastRelease: { version: "1.0.0", gitTag: "v1.0.0" },
  nextRelease: { version: "1.1.0", gitTag: "v1.1.0", type: "minor" },
  options: { repositoryUrl: REPO },
  cwd: process.cwd(),
  env: {},
  logger: { log: () => {}, error: () => {} },
});

describe("release notes", () => {
  test("lists the features and the fixes that landed", () => {
    expect(notes).toContain("publish the container image");
    expect(notes).toContain("run the image as the mount owner");
  });

  test("groups them under headings rather than emitting a bare version line", () => {
    expect(notes).toMatch(/###\s+Features/);
    expect(notes).toMatch(/###\s+Bug Fixes/);
  });

  test("leaves the types that release nothing out of the notes", () => {
    expect(notes).not.toContain("bump a linter");
  });
});
